version: 2

project_name: makakito

before:
  hooks:
    - go mod tidy

builds:
  - id: makakito
    binary: makakito
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/CyberArgonaut/makakito/cmd.version={{.Version}}
      - -X github.com/CyberArgonaut/makakito/cmd.commit={{.Commit}}
      - -X github.com/CyberArgonaut/makakito/cmd.date={{.Date}}

archives:
  - id: makakito
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - experiments/**

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
