package cmd

import (
	"bufio"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Interactive wizard to generate a starter experiment YAML",
	RunE: func(cmd *cobra.Command, _ []string) error {
		outFile, _ := cmd.Flags().GetString("output")
		reader := bufio.NewReader(os.Stdin)

		fmt.Println("makakito — Experiment Wizard")
		fmt.Println("============================")

		name := prompt(reader, "Experiment name", "My first experiment")
		targetKind := promptChoice(reader, "Target kind", []string{"docker", "kubernetes", "process"}, "docker")
		faultKind := promptChoice(reader, "Fault kind", []string{"container-stop", "container-pause", "cpu", "memory", "network-latency", "packet-loss"}, "container-stop")
		healthURL := prompt(reader, "Health check URL", "http://localhost:8080/healthz")
		env := prompt(reader, "Environment", "staging")

		yaml := generateExperimentYAML(name, targetKind, faultKind, healthURL, env)

		if outFile == "" {
			safeName := strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(name, " ", "-"), "/", "-"))
			outFile = safeName + ".yaml"
		}

		if err := os.WriteFile(outFile, []byte(yaml), 0o644); err != nil {
			return fmt.Errorf("writing experiment file: %w", err)
		}

		fmt.Printf("\n✓ Experiment saved to %s\n", outFile)
		fmt.Printf("  Validate: makakito validate %s\n", outFile)
		fmt.Printf("  Dry-run:  makakito run --dry-run %s\n", outFile)
		fmt.Printf("  Run:      makakito run %s\n", outFile)
		return nil
	},
}

func init() {
	initCmd.Flags().StringP("output", "o", "", "Output file path (default: <name>.yaml)")
	rootCmd.AddCommand(initCmd)
}

func prompt(r *bufio.Reader, label, defaultVal string) string {
	fmt.Printf("%s [%s]: ", label, defaultVal)
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	return line
}

func promptChoice(r *bufio.Reader, label string, choices []string, defaultVal string) string {
	fmt.Printf("%s (%s) [%s]: ", label, strings.Join(choices, "|"), defaultVal)
	line, _ := r.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return defaultVal
	}
	if slices.Contains(choices, line) {
		return line
	}
	fmt.Printf("Invalid choice %q, using default %q\n", line, defaultVal)
	return defaultVal
}

func generateExperimentYAML(name, targetKind, faultKind, healthURL, env string) string {
	return fmt.Sprintf(`version: "1"
name: %s
description: Generated by makakito init
labels:
  phase: "1"
  env: %s

hypothesis:
  title: Service remains healthy
  probes:
    - type: http
      url: %s
      expected_status: 200
      timeout: 5s

method:
  - type: fault
    name: Apply %s
    target:
      kind: %s
      selector:
        name: my-service
    fault:
      kind: %s
    duration: 60s
    rollback: auto

controls:
  blast_radius:
    max_targets: 1
  timeout: 5m
  environments:
    - %s
`, name, env, healthURL, faultKind, targetKind, faultKind, env)
}
